spring.application.name=url-shortener

spring.datasource.url=jdbc:mysql://localhost:3306/urlshortenerdb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

jwt.secret=97488750e2265306bfd4690d7f93c960979645e86040a59a11c476cecb438e39
jwt.expiration=172800000